# VideoShareController.py

import os
import json
from datetime import datetime


BRIDGE_FILE = "udaan_android_share.json"


class VideoShareController:

    def prepare(
        self,
        video_path,
        title="Udaan AI Video",
        description="Generated by Udaan AI",
        platform="YouTube"
    ):

        if not video_path:
            return {
                "status": "FAILED",
                "message": "Video path missing."
            }

        if not os.path.exists(video_path):
            return {
                "status": "FILE_NOT_FOUND",
                "message": "Video file not found.",
                "video_path": video_path
            }

        package = {
            "status": "READY",
            "action": "android.intent.action.SEND",
            "mime_type": "video/mp4",
            "video_path": os.path.abspath(video_path),
            "title": title,
            "description": description,
            "platform": platform,
            "founder_approved": True,
            "requires_final_confirmation": True,
            "created_at": datetime.now().isoformat()
        }

        with open(
            BRIDGE_FILE,
            "w",
            encoding="utf-8"
        ) as file:

            json.dump(
                package,
                file,
                indent=4,
                ensure_ascii=False
            )

        return package

    def get_bridge(self):

        if not os.path.exists(BRIDGE_FILE):
            return {
                "status": "NO_BRIDGE",
                "message": "Share package not created yet."
            }

        with open(
            BRIDGE_FILE,
            "r",
            encoding="utf-8"
        ) as file:

            return json.load(file)


_controller = VideoShareController()


def prepare_video_share(
    video_path,
    title="Udaan AI Video",
    description="Generated by Udaan AI",
    platform="YouTube"
):

    return _controller.prepare(
        video_path,
        title,
        description,
        platform
    )


def get_share_package():

    return _controller.get_bridge()


if __name__ == "__main__":

    print()
    print("=" * 60)
    print("       UDAAN AI — VIDEO SHARE CONTROLLER")
    print("=" * 60)

    test_path = "udaan_videos/demo.mp4"

    result = prepare_video_share(
        video_path=test_path,
        title="Udaan AI Test Video",
        description="Test video from Udaan AI",
        platform="YouTube"
    )

    print()

    print("STATUS:", result["status"])

    if result["status"] == "READY":

        print("PLATFORM:", result["platform"])
        print("ACTION:", result["action"])
        print("MIME:", result["mime_type"])
        print("FOUNDER APPROVED:",
              result["founder_approved"])
        print("FINAL CONFIRMATION:",
              result["requires_final_confirmation"])
        print("BRIDGE FILE:", BRIDGE_FILE)

    else:

        print("MESSAGE:", result["message"])

    print()
    print("=" * 60)